#ddev-generated
# If you remove the ddev-generated line above you
# are responsible for maintaining this file. DDEV will not then
# update it, for example if you add `additional_hostnames`, etc.

http:
  routers:
    youtube-probe-xhgui-80-http:
      entrypoints:
        - http-8143
      rule: HostRegexp(`^youtube-probe\.ddev\.site$`)
      
      service: "youtube-probe-xhgui-80"
      tls: false
      # middlewares:
      #   - "youtube-probe-redirectHttps"
    youtube-probe-web-80-http:
      entrypoints:
        - http-80
      rule: HostRegexp(`^youtube-probe\.ddev\.site$`)
      
      service: "youtube-probe-web-80"
      tls: false
      # middlewares:
      #   - "youtube-probe-redirectHttps"
    youtube-probe-web-8025-http:
      entrypoints:
        - http-8025
      rule: HostRegexp(`^youtube-probe\.ddev\.site$`)
      
      service: "youtube-probe-web-8025"
      tls: false
      # middlewares:
      #   - "youtube-probe-redirectHttps"
    
    
    youtube-probe-xhgui-80-https:
      entrypoints:
        - http-8142
      rule: HostRegexp(`^youtube-probe\.ddev\.site$`)
      
      service: "youtube-probe-xhgui-80"
      
      tls: true
      
    
    
    youtube-probe-web-80-https:
      entrypoints:
        - http-443
      rule: HostRegexp(`^youtube-probe\.ddev\.site$`)
      
      service: "youtube-probe-web-80"
      
      tls: true
      
    youtube-probe-web-8025-https:
      entrypoints:
        - http-8026
      rule: HostRegexp(`^youtube-probe\.ddev\.site$`)
      
      service: "youtube-probe-web-8025"
      
      tls: true
      
    

  middlewares:
    youtube-probe-redirectHttps:
      redirectScheme:
        scheme: https
        permanent: true

  services:
    youtube-probe-xhgui-80:
      loadbalancer:
        servers:
          - url: http://ddev-youtube-probe-xhgui:80
        
    
    youtube-probe-web-80:
      loadbalancer:
        servers:
          - url: http://ddev-youtube-probe-web:80
        
    youtube-probe-web-8025:
      loadbalancer:
        servers:
          - url: http://ddev-youtube-probe-web:8025
        
    
    
    

tls:
  certificates:
    - certFile: /mnt/ddev-global-cache/traefik/certs/youtube-probe.crt
      keyFile: /mnt/ddev-global-cache/traefik/certs/youtube-probe.key